name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ks-java-runtime-lib:
          - repo: 'generalmimon/kaitai_struct_java_runtime'
            ref: 'set-jdk-7-in-pom-xml'
          - repo: 'kaitai-io/kaitai_struct_java_runtime'
            ref: 'build-for-java-7'
        java-version:
          - '8'
          - '11'
          - '17'

    steps:
      - name: Checkout the KS runtime lib for Java
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.ks-java-runtime-lib.repo }}
          ref: ${{ matrix.ks-java-runtime-lib.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: ks-runtime-built-by-${{ matrix.java-version }}
          path: target/kaitai-struct-runtime-0.9.jar

  run:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        built-by-java-version:
          - '8'
          - '11'
          - '17'
        java-version:
          - '8'
          - '11'
          - '17'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - uses: actions/download-artifact@v3
        with:
          name: ks-runtime-built-by-${{ matrix.built-by-java-version }}
      - name: Compile
        run: javac -encoding UTF-8 -cp kaitai-struct-runtime-0.9.jar -d bin *.java
      - name: Run
        run: java -cp 'bin:kaitai-struct-runtime-0.9.jar' App
